[workspace]
members = [
    "simulation",
    "shaders/mouse-shader",
    "shaders/compute-shader",
    "run-wasm",
]
resolver = "3"


[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = [
    'cfg(target_arch, values("spirv"))',
] }

[workspace.dependencies]
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu", rev = "de03e8d8c997c68aed1a950863c0d79ba9bd8c72" }
