[package]
name = "compute-shader"
version = "0.0.0"
edition = "2024"
publish = false

[lints]
workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
shared = { path = "../../shaders/shared" }
spirv-std = { workspace = true }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
rayon = "1.5"

[features]
movable_solid_check_horizontal = []
